Repository RomanHav/kalyna-group, pull requests merged in 2025-01, with the labels that each got.

#52 finish stack slider desktop, fix arrow on accordion
  .eslintrc.json
  public/adobe-illustrator.svg
  public/adobe-photoshop.svg
  public/blender.svg
  public/express.svg
  public/figma.svg
  public/javascript.svg
  public/mongodb.svg
  public/nextjs.svg
  public/react.svg
  public/shopify.svg
  public/tailwind.svg
  public/typescript.svg
  src/app/components/Footer/Footer.tsx
  src/app/components/OurStack.tsx
  src/app/components/OurStackPart.tsx
  src/app/components/SwiperNext.tsx
  src/app/globals.css
  stack.json
  tailwind.config.ts
  tsconfig.json
Labels: good first issue

#54 update form
  package-lock.json
  package.json
  src/app/components/AboutUs/AboutUs.module.css
  src/app/components/AboutUs/AboutUs.tsx
  src/app/components/FormSecond.tsx
  src/app/components/NavBar/NavBar.tsx
  src/app/components/StepFifth.tsx
  src/app/components/StepFirst.tsx
  src/app/components/StepFourth.tsx
  src/app/components/StepSecond.tsx
  src/app/components/StepThird.tsx
  src/app/components/StepsForm/FormModel.tsx
  src/app/components/StepsForm/FormSecond.tsx
  src/app/components/StepsForm/ProgressLine.tsx
  src/app/components/StepsForm/StepFifth.tsx
  src/app/components/StepsForm/StepFirst.tsx
  src/app/components/StepsForm/StepFourth.tsx
  src/app/components/StepsForm/StepSecond.tsx
  src/app/components/StepsForm/StepThird.tsx
  src/app/components/StepsForm/Steps.tsx
  src/app/page.tsx
Labels: help wanted

#56 adaptive about-us
  src/app/about-us/page.tsx
  src/app/components/ArrowCases.tsx
  src/app/components/HowWeWork.tsx
  src/app/components/HowWeWorkPart.tsx
  src/app/components/OurStack.tsx
  src/app/components/OurStackPart.tsx
  src/app/components/OurTeam.tsx
  src/app/components/WhoWeAre.tsx
  src/app/page.tsx
  src/app/utils/lenis.ts
Labels: good first issue

#57 edit server, edit form
  server/src/app.js
  server/src/controllers/clients.js
  server/src/db/models/clients.js
  server/src/index.js
  server/src/services/servicesKlaviyo.js
  src/app/about-us/page.tsx
  src/app/components/Cases.tsx
  src/app/components/CasesPart.tsx
  src/app/components/ContactUsModal.tsx
  src/app/components/Form.tsx
  src/app/components/Form/FormInitialValues.tsx
  src/app/components/HeaderVideo/HeaderVideo.tsx
  src/app/components/HowWeWork/HowWeWork.tsx
  src/app/components/HowWeWork/HowWeWorkPart.tsx
  src/app/components/NavBar/NavBar.tsx
  src/app/components/OurStack/OurStack.tsx
  src/app/components/OurStack/OurStackPart.tsx
  src/app/components/OurTeam/OurTeam.tsx
  src/app/components/OurTeam/OurTeamPart.tsx
  src/app/components/Services/Services.tsx
  src/app/components/StepsForm/FormSecond.tsx
  src/app/components/StepsForm/StepFourth.tsx
  src/app/page.tsx
  src/app/redux/formValues/operations.ts
Labels: good first issue

#58 add validation
  package-lock.json
  package.json
  src/app/components/Form/FormInitialValues.tsx
  src/app/components/Form/FormValidationSchema.tsx
  src/app/components/StepsForm/FormSecond.tsx
  src/app/components/StepsForm/StepFifth.tsx
  src/app/components/StepsForm/StepFirst.tsx
  src/app/components/StepsForm/StepFourth.tsx
  src/app/components/StepsForm/StepSecond.tsx
  src/app/components/StepsForm/StepThird.tsx
  src/app/components/StepsForm/Succes.tsx
  steps.json
Labels: good first issue

#60 finish e-commerce
  commerceFaq.json
  package-lock.json
  package.json
  public/Subtract.svg
  src/app/components/ArrowCases.tsx
  src/app/components/CommerceImage.tsx
  src/app/components/Faq/Faq.tsx
  src/app/components/Faq/FaqPart.tsx
  src/app/components/HeaderService.tsx
  src/app/components/OurExpertise/OurExpertise.tsx
  src/app/e-commerce/page.tsx
  src/app/layout.tsx
  src/app/utils/parallax.ts
  tailwind.config.ts
Labels: good first issue

#86 edit video format with alpha channel
  public/3d-animation-osx.mp4
  src/app/3d-design/page.tsx
  src/app/components/HeaderService.tsx
Labels: good first issue

#87 adaptive/3d-design
  public/AE.mp4
  src/app/3d-design/page.tsx
Labels: help wanted

#89 edit video
  public/3d-animation.mov
Labels: question

#95 add mobile services
  src/app/components/MobileServices.tsx
Labels: good first issue

#96 add mobile services
  src/app/components/DesktopServices.tsx
  src/app/components/MobileServices.tsx
  src/app/components/Services/ServicePart.tsx
  src/app/components/Services/Services.tsx
Labels: good first issue
